application: aep-s1
version: 2
runtime: python27
api_version: 1
threadsafe: no

default_expiration: '3650d'

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /media
  static_dir: _generated_media
  secure: optional

- url: /.*
  script: common/appenginepatch/main.py
  secure: optional

libraries:
- name: django
  version: "1.2"
- name: lxml
  version: "2.3"

inbound_services:
  - warmup

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*/.git/.*
- ^(.*/)?\.git.*
- ^(.*/)?\.gitignore
- ^(.*/)?.*\.cld
- ^(.*/)?.*/.svn/.*
- ^(.*/)?\.svnignore
- ^(.*/)?.*/tests/.*
- ^(.*/)?scripts/.*
- ^(.*/)?.*\.sh
- ^(.*/)?.*\.bat
- ^(.*/)?.*\.rst
- ^(.*/)?.*/Makefile
- ^(.*/)?.*/README.*
- ^(.*/)?\*.esproj
- ^(.*/)?\.settings
- ^(.*/)?\.project
- ^(.*/)?\.pydevproject